-- ============================================================
-- JOSEO - PRECIOS WEB AUTOMÁTICOS (AISLADOS)
--
-- No modifica ni borra prices, joseo_community_prices ni branches.
-- Los precios web se guardan en tablas separadas y se agregan a
-- joseo_prices_nearby como una segunda fuente.
-- ============================================================

begin;

create table if not exists public.web_price_sources (
  id bigint generated by default as identity primary key,
  name text not null,
  base_url text not null,
  parser_type text not null default 'vtex',
  store_id bigint references public.stores(id) on delete cascade,
  branch_id bigint references public.branches(id) on delete cascade,
  enabled boolean not null default false,
  last_started_at timestamptz,
  last_success_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint web_price_sources_parser_check
    check (parser_type in ('vtex', 'jsonld')),
  constraint web_price_sources_url_check
    check (base_url ~ '^https?://')
);

create unique index if not exists web_price_sources_branch_url_idx
  on public.web_price_sources (coalesce(branch_id, 0), lower(base_url));

create table if not exists public.web_price_observations (
  id bigint generated by default as identity primary key,
  source_id bigint not null references public.web_price_sources(id) on delete cascade,
  store_id bigint not null references public.stores(id) on delete cascade,
  branch_id bigint not null references public.branches(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  external_product_id text not null,
  product_name text not null,
  brand text,
  size_text text,
  price numeric(12,2) not null check (price > 0),
  regular_price numeric(12,2) check (regular_price is null or regular_price > 0),
  currency text not null default 'DOP',
  is_offer boolean not null default false,
  available boolean not null default true,
  observed_at timestamptz not null default now(),
  observed_date date not null default current_date,
  source_url text not null,
  source_type text not null default 'official_web',
  verification_status text not null default 'verified',
  import_status text not null default 'imported',
  note text,
  raw jsonb,
  created_at timestamptz not null default now(),
  constraint web_price_observations_currency_check
    check (currency in ('DOP', 'USD')),
  constraint web_price_observations_status_check
    check (import_status in ('imported', 'unmatched', 'rejected', 'error')),
  constraint web_price_observations_verification_check
    check (verification_status in ('verified', 'pending', 'rejected')),
  constraint web_price_observations_daily_unique
    unique (source_id, external_product_id, observed_date)
);

create index if not exists web_price_observations_latest_idx
  on public.web_price_observations (branch_id, product_id, observed_at desc);

create index if not exists web_price_observations_status_idx
  on public.web_price_observations (import_status, verification_status, observed_at desc);

alter table public.web_price_sources enable row level security;
alter table public.web_price_observations enable row level security;

drop policy if exists joseo_web_prices_public_read on public.web_price_observations;
create policy joseo_web_prices_public_read
  on public.web_price_observations
  for select
  to anon, authenticated
  using (
    import_status = 'imported'
    and verification_status = 'verified'
    and available = true
  );

revoke all on public.web_price_sources from anon, authenticated;
revoke all on public.web_price_observations from anon, authenticated;
grant select on public.web_price_observations to anon, authenticated;

-- Consulta de control para el panel/SQL Editor:
-- select id, name, base_url, parser_type, branch_id, enabled,
--        last_success_at, last_error
-- from public.web_price_sources
-- order by id;

-- ============================================================
-- Integra precios web con el radar geolocalizado existente.
-- Se conserva la firma y el resultado de la función actual.
-- ============================================================

create or replace function public.joseo_prices_nearby(
  p_lat double precision,
  p_lng double precision,
  p_radius_km double precision default 20
)
returns table (
  record_key text,
  source_kind text,
  community_price_id bigint,
  official_price_id bigint,
  user_id text,
  product_id bigint,
  product text,
  branch_id bigint,
  branch text,
  store_id bigint,
  supermarket text,
  price double precision,
  regular_price double precision,
  is_offer boolean,
  observed_at text,
  source_period text,
  source_type text,
  source_quality text,
  source_url text,
  source_document text,
  note text,
  photo_url text,
  confirmed_count integer,
  incorrect_count integer,
  verified_place boolean,
  can_vote boolean,
  xp_eligible boolean,
  radar_candidate boolean,
  distance_km double precision,
  is_best_nearby boolean
)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  with validated_input as (
    select
      case when p_lat between -90 and 90 then p_lat else null end as latitude,
      case when p_lng between -180 and 180 then p_lng else null end as longitude,
      least(greatest(coalesce(p_radius_km, 20), 1), 50) as radius_km
  ),
  branch_candidates as (
    select
      b.id::bigint as branch_id,
      (
        6371 * acos(
          least(1.0, greatest(-1.0,
            cos(radians(i.latitude)) * cos(radians(b.latitude))
            * cos(radians(b.longitude) - radians(i.longitude))
            + sin(radians(i.latitude)) * sin(radians(b.latitude))
          ))
        )
      )::double precision as distance_km,
      i.radius_km
    from public.branches b
    join public.stores s on s.id = b.store_id
    cross join validated_input i
    where i.latitude is not null
      and i.longitude is not null
      and b.latitude is not null
      and b.longitude is not null
      and b.active = true
      and s.active = true
      and b.verification_status = 'verified'
      and s.verification_status = 'verified'
  ),
  nearby_branches as (
    select branch_id, distance_km
    from branch_candidates
    where distance_km <= radius_km
  ),
  all_prices as (
    -- Fuente comunitaria/oficial que JOSEO ya tiene funcionando.
    select
      ap.record_key::text as record_key,
      ap.source_kind::text as source_kind,
      ap.community_price_id::bigint as community_price_id,
      ap.official_price_id::bigint as official_price_id,
      ap.user_id::text as user_id,
      ap.product_id::bigint as product_id,
      ap.product::text as product,
      ap.branch_id::bigint as branch_id,
      ap.branch::text as branch,
      ap.store_id::bigint as store_id,
      ap.supermarket::text as supermarket,
      ap.price::double precision as price,
      ap.regular_price::double precision as regular_price,
      coalesce(ap.is_offer, false)::boolean as is_offer,
      ap.observed_at::timestamptz as observed_at,
      coalesce(ap.source_period, '')::text as source_period,
      coalesce(ap.source_type, '')::text as source_type,
      coalesce(ap.source_quality, '')::text as source_quality,
      coalesce(ap.source_url, '')::text as source_url,
      coalesce(ap.source_document, '')::text as source_document,
      coalesce(ap.note, '')::text as note,
      ap.photo_url::text as photo_url,
      coalesce(ap.confirmed_count, 0)::integer as confirmed_count,
      coalesce(ap.incorrect_count, 0)::integer as incorrect_count,
      coalesce(ap.verified_place, false)::boolean as verified_place,
      coalesce(ap.can_vote, false)::boolean as can_vote,
      coalesce(ap.xp_eligible, false)::boolean as xp_eligible,
      coalesce(ap.radar_candidate, false)::boolean as radar_candidate
    from public.joseo_all_prices ap

    union all

    -- Fuente web: solo productos emparejados con products y observaciones actuales.
    select
      ('web:' || w.id)::text as record_key,
      'official'::text as source_kind,
      null::bigint as community_price_id,
      w.id::bigint as official_price_id,
      ''::text as user_id,
      w.product_id::bigint,
      coalesce(p.name, w.product_name)::text as product,
      w.branch_id::bigint,
      b.name::text as branch,
      w.store_id::bigint,
      s.name::text as supermarket,
      w.price::double precision,
      w.regular_price::double precision,
      w.is_offer::boolean,
      w.observed_at::timestamptz,
      'web'::text as source_period,
      w.source_type::text,
      'official-site'::text as source_quality,
      w.source_url::text,
      ''::text as source_document,
      coalesce(w.note, '')::text,
      null::text as photo_url,
      0::integer as confirmed_count,
      0::integer as incorrect_count,
      true::boolean as verified_place,
      false::boolean as can_vote,
      false::boolean as xp_eligible,
      w.is_offer::boolean as radar_candidate
    from public.web_price_observations w
    join public.products p on p.id = w.product_id and p.active = true
    join public.branches b on b.id = w.branch_id
    join public.stores s on s.id = w.store_id
    where w.import_status = 'imported'
      and w.verification_status = 'verified'
      and w.available = true
      and w.price > 0
  ),
  eligible_prices as (
    select
      ap.*,
      nb.distance_km,
      row_number() over (
        partition by ap.product_id, ap.branch_id
        order by ap.observed_at desc nulls last, ap.record_key desc
      ) as freshness_rank
    from all_prices ap
    join nearby_branches nb on nb.branch_id = ap.branch_id
    where ap.verified_place = true
      and ap.price is not null
      and ap.price > 0
  ),
  latest_branch_prices as (
    select *
    from eligible_prices
    where freshness_rank = 1
  ),
  ranked_prices as (
    select
      lp.*,
      dense_rank() over (
        partition by lp.product_id
        order by lp.price asc
      ) as nearby_price_rank
    from latest_branch_prices lp
  )
  select
    rp.record_key::text,
    rp.source_kind::text,
    rp.community_price_id::bigint,
    rp.official_price_id::bigint,
    rp.user_id::text,
    rp.product_id::bigint,
    rp.product::text,
    rp.branch_id::bigint,
    rp.branch::text,
    rp.store_id::bigint,
    rp.supermarket::text,
    rp.price::double precision,
    rp.regular_price::double precision,
    coalesce(rp.is_offer, false)::boolean,
    rp.observed_at::text,
    coalesce(rp.source_period, '')::text,
    coalesce(rp.source_type, '')::text,
    coalesce(rp.source_quality, '')::text,
    coalesce(rp.source_url, '')::text,
    coalesce(rp.source_document, '')::text,
    coalesce(rp.note, '')::text,
    rp.photo_url::text,
    coalesce(rp.confirmed_count, 0)::integer,
    coalesce(rp.incorrect_count, 0)::integer,
    coalesce(rp.verified_place, false)::boolean,
    coalesce(rp.can_vote, false)::boolean,
    coalesce(rp.xp_eligible, false)::boolean,
    coalesce(rp.radar_candidate, false)::boolean,
    round(rp.distance_km::numeric, 2)::double precision,
    (rp.nearby_price_rank = 1)::boolean
  from ranked_prices rp
  order by lower(rp.product), rp.price asc, rp.distance_km asc;
$$;

revoke all on function public.joseo_prices_nearby(
  double precision, double precision, double precision
) from public;

grant execute on function public.joseo_prices_nearby(
  double precision, double precision, double precision
) to anon, authenticated;

commit;

-- ============================================================
-- Configuración de prueba (no se activa automáticamente):
--
-- insert into public.web_price_sources
--   (name, base_url, parser_type, store_id, branch_id, enabled)
-- select 'La Sirena - catálogo web piloto', 'https://www.sirena.do', 'vtex',
--        s.id, b.id, false
-- from public.stores s
-- join public.branches b on b.store_id = s.id
-- where s.name = 'La Sirena' and b.name = 'Sarasota'
-- limit 1;
--
-- Después de revisar la sucursal y la URL:
-- update public.web_price_sources
-- set enabled = true, updated_at = now()
-- where name = 'La Sirena - catálogo web piloto';
